[broker]
url = "https://aktin-test-broker.klinikum.rwth-aachen.de"
api_key = "xxxAdmin1234"

[requests]
tag = "pandemieradar"

[misc]
temp_dir = 'C:\\Users\\whoy\\PycharmProjects\\LOC_Calculator\\src'

[rscript]
script_path = 'C:\\Users\\whoy\\PycharmProjects\\LOC_Calculator\\src\\resources\\LOSCalculator.R'
r_directory = 'C:\\Program Files\\R\\R-4.3.1\\bin'

[SFTP]
HOST = "127.0.0.1"
USERNAME = "sftpuser"
PASSWORD = "sftppassword"
TIMEOUT = "25"
FOLDERNAME = "rki"
